"""Training dataset for InstrAct pretraining.

The annotation JSON is keyed by the positive caption.  Masked action modeling
uses the offline ``mam_mask_candidates`` annotations generated by
``tools/annotate_mam_candidates.py``.  At each access, one candidate word is
selected and all of its CLIP BPE pieces are marked in ``action_mask``.
"""

from __future__ import annotations

import json
import os
import random
from pathlib import Path

import ffmpeg
import numpy as np
import torch
from torch.utils.data import Dataset

from models.third_party.internvideo_compat.simple_tokenizer import SimpleTokenizer


class HT100MDataLoader(Dataset):
    """Load video-caption examples and action-centric text annotations."""

    def __init__(
        self,
        video_root="",
        caption_json="",
        min_time=3.2,
        fps=10,
        num_frames=16,
        size=224,
        num_hn=12,
        num_vp=6,
        crop_only=False,
        max_words=32,
        uniform_window=5.0,
        hard_negative_type="both",
    ):
        if not isinstance(size, int):
            raise TypeError("size must be an integer")
        if max_words < 3:
            raise ValueError("max_words must leave room for SOT, text, and EOT")

        self.video_root = Path(video_root)
        self.min_time = float(min_time)
        self.fps = float(fps)
        self.num_frames = int(num_frames)
        self.size = size
        self.crop_only = bool(crop_only)
        self.max_words = int(max_words)
        self.max_negatives = int(num_hn)
        self.max_verbs = int(num_vp)
        self.max_text = 2 + self.max_negatives + self.max_verbs
        self.uniform_window = float(uniform_window)
        if hard_negative_type not in {"both", "verb", "order"}:
            raise ValueError("hard_negative_type must be both, verb, or order")
        self.hard_negative_type = hard_negative_type
        self.tokenizer = SimpleTokenizer()

        with open(caption_json, "r", encoding="utf-8") as handle:
            caption_dict = json.load(handle)
        if not isinstance(caption_dict, dict):
            raise ValueError("caption_json must contain an object keyed by caption")

        self.samples = []
        video_indices = {}
        for caption, info in caption_dict.items():
            sample = self._prepare_sample(caption, info)
            if sample is not None:
                video_id = sample["video_id"]
                if video_id not in video_indices:
                    video_indices[video_id] = len(video_indices)
                sample["group_id"] = video_indices[video_id]
                self.samples.append(sample)

        print(
            f"[HT100MDataLoader] Loaded {len(self.samples)} "
            "caption-video pairs."
        )

    @staticmethod
    def _clean_strings(values):
        if not isinstance(values, list):
            return []
        return [
            value.strip()
            for value in values
            if isinstance(value, str) and value.strip()
        ]

    @staticmethod
    def _clean_candidates(caption, values):
        if not isinstance(values, list):
            return []

        candidates = []
        for candidate in values:
            if not isinstance(candidate, dict):
                continue
            try:
                start = int(candidate["char_start"])
                end = int(candidate["char_end"])
            except (KeyError, TypeError, ValueError):
                continue
            word = candidate.get("word")
            if (
                not isinstance(word, str)
                or start < 0
                or end <= start
                or end > len(caption)
                or caption[start:end] != word
            ):
                continue
            candidates.append(
                {
                    "word": word,
                    "char_start": start,
                    "char_end": end,
                    "phrase": candidate.get("phrase", ""),
                    "method": candidate.get("method", ""),
                }
            )
        return candidates

    def _prepare_sample(self, caption, info):
        if not isinstance(caption, str) or not isinstance(info, dict):
            return None

        video_id = info.get("video_id")
        if not isinstance(video_id, str) or not video_id:
            return None
        video_path = self.video_root / f"{video_id}.mp4"
        if not video_path.is_file():
            return None

        try:
            start = float(info.get("start", 0.0))
            end = float(info.get("end", 0.0))
        except (TypeError, ValueError):
            return None
        if end - start < self.min_time:
            difference = self.min_time - (end - start)
            start = max(0.0, start - difference / 2.0)
            end = start + self.min_time

        return {
            "caption": caption,
            "video_id": video_id,
            "video_path": str(video_path),
            "start": start,
            "end": end,
            "hard_negatives": self._clean_strings(
                info.get("hard_negatives") or []
            ),
            "order_swapped_hn": self._clean_strings(
                info.get("order_swapped_hn") or []
            ),
            "verb_phrases": self._clean_strings(
                info.get("verb_phrases") or []
            ),
            "mam_mask_candidates": self._clean_candidates(
                caption, info.get("mam_mask_candidates") or []
            ),
        }

    def __len__(self):
        return len(self.samples)

    def _decode_video(self, video_path, start, end):
        """Decode an expanded temporal window and uniformly sample frames."""
        for attempt in range(3):
            try:
                window_start = max(0.0, start - self.uniform_window)
                window_end = end + self.uniform_window
                duration = max(0.1, window_end - window_start)
                command = (
                    ffmpeg.input(
                        video_path,
                        ss=window_start,
                        t=duration + 0.1,
                        threads=1,
                    )
                    .filter("fps", fps=self.fps)
                )

                if self.crop_only:
                    command = command.crop(
                        f"(iw - {self.size})*0.5",
                        f"(ih - {self.size})*0.5",
                        str(self.size),
                        str(self.size),
                    )
                else:
                    command = (
                        command.crop(
                            "(iw - min(iw,ih))*0.5",
                            "(ih - min(iw,ih))*0.5",
                            "min(iw,ih)",
                            "min(iw,ih)",
                        )
                        .filter("scale", self.size, self.size)
                    )

                output, _ = (
                    command.output(
                        "pipe:",
                        format="rawvideo",
                        pix_fmt="rgb24",
                        threads=1,
                    )
                    .global_args("-filter_threads", "1")
                    .run(capture_stdout=True, quiet=True)
                )
                frame_size = self.size * self.size * 3
                array = np.frombuffer(output, dtype=np.uint8)
                if array.size == 0 or array.size % frame_size:
                    raise ValueError("ffmpeg returned an invalid frame buffer")

                decoded = array.reshape(-1, self.size, self.size, 3)
                if len(decoded) >= self.num_frames:
                    indices = np.linspace(
                        0,
                        len(decoded) - 1,
                        self.num_frames,
                        dtype=int,
                    )
                    decoded = decoded[indices]
                else:
                    padding = np.zeros(
                        (
                            self.num_frames - len(decoded),
                            self.size,
                            self.size,
                            3,
                        ),
                        dtype=np.uint8,
                    )
                    decoded = np.concatenate((decoded, padding), axis=0)

                video = (
                    torch.from_numpy(decoded.copy())
                    .permute(3, 0, 1, 2)
                    .float()
                    .div_(255.0)
                )
                mean = video.new_tensor(
                    (0.48145466, 0.4578275, 0.40821073)
                )[:, None, None, None]
                std = video.new_tensor(
                    (0.26862954, 0.26130258, 0.27577711)
                )[:, None, None, None]
                return (video - mean) / std
            except (ffmpeg.Error, ValueError):
                if attempt == 2:
                    return torch.zeros(
                        (3, self.num_frames, self.size, self.size),
                        dtype=torch.float32,
                    )

        raise RuntimeError("unreachable")

    def tokenize(self, texts, context_length=None):
        """Tokenize text with the CLIP SOT/EOT convention."""
        context_length = context_length or self.max_words
        if isinstance(texts, str):
            texts = [texts]

        sot = self.tokenizer.encoder["<|startoftext|>"]
        eot = self.tokenizer.encoder["<|endoftext|>"]
        result = torch.zeros(
            (len(texts), context_length),
            dtype=torch.long,
        )
        for row, text in enumerate(texts):
            tokens = [sot, *self.tokenizer.encode(text), eot]
            if len(tokens) > context_length:
                tokens = tokens[:context_length]
                tokens[-1] = eot
            result[row, : len(tokens)] = torch.tensor(tokens)
        return result

    def _candidate_token_mask(self, caption, candidate):
        """Map an annotated character span to all of its CLIP BPE positions."""
        start = candidate["char_start"]
        end = candidate["char_end"]

        # CLIP BPE is applied independently to regex-delimited words. Counting
        # the BPE pieces in both prefixes therefore maps a complete annotated
        # word to its exact half-open token span. Position zero is SOT.
        token_start = 1 + len(self.tokenizer.encode(caption[:start]))
        token_end = 1 + len(self.tokenizer.encode(caption[:end]))

        mask = torch.zeros(self.max_words, dtype=torch.bool)
        # The final position is reserved for EOT when a caption is truncated.
        if token_start < token_end and token_end <= self.max_words - 1:
            mask[token_start:token_end] = True
        return mask

    def _get_action_mask(self, sample):
        """Select one valid action word dynamically and mask all its BPE pieces."""
        candidates = list(sample["mam_mask_candidates"])
        random.shuffle(candidates)
        for candidate in candidates:
            action_mask = self._candidate_token_mask(
                sample["caption"], candidate
            )
            if action_mask.any():
                return action_mask
        return torch.zeros(self.max_words, dtype=torch.bool)

    def _select_hard_negatives(self, sample):
        order_negatives = (
            sample["order_swapped_hn"]
            if self.hard_negative_type in {"both", "order"} else []
        )
        verb_negatives = (
            sample["hard_negatives"]
            if self.hard_negative_type in {"both", "verb"} else []
        )
        negatives = list(order_negatives[: self.max_negatives])
        remaining = self.max_negatives - len(negatives)
        if remaining > 0:
            if len(verb_negatives) > remaining:
                negatives.extend(random.sample(verb_negatives, remaining))
            else:
                negatives.extend(verb_negatives)
        return negatives

    def _get_text(self, sample):
        caption = sample["caption"]
        negatives = self._select_hard_negatives(sample)
        verbs = sample["verb_phrases"][: self.max_verbs]
        num_verbs = len(verbs)

        positive_and_negatives = [caption, *negatives]
        mam_and_verbs = [caption, *verbs]
        first_ids = self.tokenize(positive_and_negatives)
        second_ids = self.tokenize(mam_and_verbs)

        first_padding = 1 + self.max_negatives - first_ids.shape[0]
        if first_padding:
            first_ids = torch.cat(
                (
                    first_ids,
                    torch.zeros(
                        (first_padding, self.max_words),
                        dtype=torch.long,
                    ),
                )
            )
        second_padding = 1 + self.max_verbs - second_ids.shape[0]
        if second_padding:
            second_ids = torch.cat(
                (
                    second_ids,
                    torch.zeros(
                        (second_padding, self.max_words),
                        dtype=torch.long,
                    ),
                )
            )

        text_ids = torch.cat((first_ids, second_ids))
        hard_negative_mask = torch.ones(
            (1 + self.max_negatives, 1),
            dtype=torch.long,
        )
        hard_negative_mask[: 1 + len(negatives)] = 0
        action_mask = self._get_action_mask(sample)
        return text_ids, num_verbs, hard_negative_mask, action_mask

    def __getitem__(self, index):
        sample = self.samples[index]
        video = self._decode_video(
            sample["video_path"],
            sample["start"],
            sample["end"],
        )
        text, num_verbs, text_mask, action_mask = self._get_text(sample)
        return {
            "idx": sample["group_id"],
            "video": video,
            "text": text,
            "text_mask": text_mask,
            "num_verbs": num_verbs,
            "action_mask": action_mask,
        }


# Backward-compatible name used by the original training scripts.
HT100M_DataLoader = HT100MDataLoader
